name: ex3_example
description: A sample command-line application
#dependencies:
#  unittest: any

name: ex3_example
version: 0.0.1
author: Jean-Francois Robichaud
description: An example how to use ex3 library.
dependencies:
  ex3:
    git: git://github.com/jean88/ex03.git